export interface IShader {
	baseVertex: WebGLShader,
	clear: WebGLShader,
	color:  WebGLShader,
	background: WebGLShader,
	display:  WebGLShader,
	displayBloom: WebGLShader,
	displayShading:  WebGLShader,
	displayBloomShading:  WebGLShader,
	bloomPreFilter: WebGLShader,
	bloomBlur: WebGLShader,
	bloomFinal: WebGLShader,
	splat: WebGLShader,
	advectionManualFiltering:  WebGLShader,
	advection: WebGLShader,
	divergence:  WebGLShader,
	curl: WebGLShader,
	vorticity: WebGLShader,
	pressure: WebGLShader,
	gradientSubtract: WebGLShader,
}
